### ISSUE TITLE
function ob_get_clean stops work,when many requests send to server

### ISSUE THREAD

**Issue by avriltank** [peachpiecompiler/peachpie#1007]
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at Pchp.Core.BufferedOutput.DecreaseLevel(Boolean flush)
   at Pchp.Library.Output.EndInternal(Context ctx, Boolean flush)
   at Pchp.Library.Output.ob_get_clean(Context ctx)
   at <Root>chenfa/myconfig.route_php.anonymous@function(Closure <closure>, Request request) in D:\chenfa\dotnet_php_proj\four_console\phpapp\chenfa\myconfig\route.php:line 10
```

**Comment by jakubmisek** [comment]
thanks for the issue; do you have a test case for that?

**Comment by avriltank** [comment]
[four_console.zip](https://github.com/peachpiecompiler/peachpie/files/7775697/four_console.zip)
This is the simple case!when i use the command " wrk -c100 -t16 -d10s http://192.168.50.1:9898 ",the error occur

**Comment by jakubmisek** [comment]
thanks, great sample! I like the interoperability stuff.

I'm not getting the same eception, although sometimes I get `System.NullReferenceException`. I'll keep testing

**Comment by jakubmisek** [comment]
I see!

The problem is, the C# code is multithreaded but it reuses a single instance of `Context ctx` across all the threads.

`Context` is not thread safe. It actually represents a single PHP request/single PHP app;

It can be reused, but threading matters - or - you can create and dispose an instance of `Context` (https://docs.peachpie.io/api/ref/context/#construction). In case you need to call a PHP function on a newly created `Context ctx`, you can include a script using
```c#
using (var ctx = Context.CreateEmpty()) {
   ctx.Include("", "main.php");
   ctx.Call("http_server_message");
}
```

**Comment by avriltank** [comment]
Thanks very much!I see the context is not thread safe!
