### ISSUE TITLE
csharp-php-hybrid sample can not run

### ISSUE THREAD

**Issue by vvtll** [peachpiecompiler/peachpie#1010]
see https://github.com/iolevel/peachpie-samples/issues/10

**Comment by jakubmisek** [comment]
we'll check that!

**Comment by jakubmisek** [comment]
closing here

**Comment by vvtll** [comment]
Thanks!But why can't it work when I delete part of the code!
```
Unhandled exception. Pchp.Core.PhpFatalErrorException: Script 'functions.php' inclusion failed. Cause: Script file 'functions.php' not found. Search paths: include_path is '.', working directory is '' 
   at Pchp.Core.PhpException.Throw(PhpError error, String message)
   at Pchp.Core.PhpException.Throw(PhpError error, String formatString, String[] args)
   at Pchp.Core.Context.HandleMissingScript(String cd, String path, Boolean throwOnError)
   at Pchp.Core.Context.Include(String cd, String path, PhpArray locals, Object this, RuntimeTypeHandle self, Boolean once, Boolean throwOnError)
   at Pchp.Core.Context.Include(String dir, String path, Boolean once, Boolean throwOnError)
   at csharpapp.Program.Main() in /home/vvtll/proj/test_php/csharpapp/Program.cs:line 22
```
[test_php.zip](https://github.com/peachpiecompiler/peachpie/files/7786810/test_php.zip)

**Comment by vvtll** [comment]
I don't understand how the contex object Include work!I try to set Rootpath or workdirectory!They also don‘t work!But if the functions.php is a php class!when include functions.php in the csharp code,and use new phpclass object to get a instance of the php class,there is no error

**Comment by jakubmisek** [comment]
@vvtll thanks for the questions; you are right, in the case of a custom `Context` this is a bit tricky. 

All the `.php` script files are compiled and stored in DLL with relative paths. Since then, the RootPath and WorkingDirectory can be whatever you set actually. 

All the compiled scripts "appear" to be in `<RootPath>/<RelativePath>` at run time.

The working directory is used during the include resolution, and also for other PHP' file system operations (like `fopen`).

**The PhpFatalErrorException** - is probably our fault; The `phplib.dll` file with your compiled script files needs to be reflected first and mostly it happens automatically.

Try adding the following to your code, we'll update the sample code, incl. the brief explanation as well.

```c#
Context.AddScriptReference( Assembly.Load( "phplib" ) );
```

It gets called "automatically" when .NET JIT reaches any PHP class.
