### ISSUE TITLE
No Custom Attributes

### ISSUE THREAD

**Issue by hadi77ir** [peachpiecompiler/peachpie#106]
There is no custom attribute on classes, properties, variables, etc. in PHP.
Would it get implemented in Peachpie in future (useful for both-way .NET interop)?

**Comment by jakubmisek** [comment]
This will be achieved in a backward compatible way - through PHPDoc comments. Such code will be still a valid PHP code.

We already support our custom attribute `@appstatic` (https://www.peachpie.io/2017/11/caching-across-requests-php.html)

In order to support .NET attributes in future, we may support something like:
```php
/**
 * @[CustomAttribute(A, B, C)]
 */
```
