### ISSUE TITLE
sort method compare not supported - throw error using WP 6.4.3 - update.php

### ISSUE THREAD

**Issue by benyaminl** [peachpiecompiler/peachpie#1135]
I just curious, does the sort function for method comparer really isn't implemented? 
I got error by running the home page of Wordpress in peachpie. 

![image](https://github.com/peachpiecompiler/peachpie/assets/2817332/d902ddb9-3ad9-4e34-affc-97389aad15af)

**Comment by jakubmisek** [comment]
It has been implemented recently.

What version of wpdotnet/peachpie do you use?

**Comment by jakubmisek** [comment]
The latest WordPress we've checked is [6.3.1](https://www.nuget.org/packages/PeachPied.WordPress/6.3.1-rc-016).

The sort() with flags on the screenshot has been supported since PeachPie 1.1.9. (https://github.com/peachpiecompiler/peachpie/commit/f67b04ff9aae3cf20d211403043438b7bb38cdd1)

What is your setup?
