### ISSUE TITLE
Where is peach.exe or pchp.exe?

### ISSUE THREAD

**Issue by GERMANOCARELLA** [peachpiecompiler/peachpie#166]
Hi, I installed peachpie compiler on my windows 10 machine with visual studio code. I tried also to install with dotnet and I'm able to create a project.
So, I can't find peach.exe command line compiler.
I'm visually empaired and I can't see videos you posted.
I tried to open solution in my visual studio 2017 and I tried to compile all solution. I receive 305 errors and more than 200 warnings.
There is a way to have peach.exe running on my machine? 
There is a way to have a peachpie repl such as psysh?
Thanks!

**Comment by Wulfklaue** [comment]
I think you are confused, Peach Pie uses the default dotnet compile structure.

Simple do for a website:
```
dotnet new -i Peachpie.Templates::*
dotnet new web -lang PHP
cd Server
dotnet run
```

Or for Console:

```
dotnet new -i Peachpie.Templates::*
dotnet new console -lang PHP
dotnet run
```

Or build the project with dotnet build ... All Peach Pie does is transcode PHP style syntax to C#.

**Comment by jakubmisek** [comment]
@GERMANOCARELLA glad you are playing with our little project!

`peach.exe` is a command line utility used mainly for testing and because people are used to simple command line utilities. There are no official binaries and you would have to compile `src/compiler/peach` project in order to get it.

It is recommended to use `dotnet build` command and a project file, like described by @Wulfklaue
