### ISSUE TITLE
composer questions

### ISSUE THREAD

**Issue by liesauer** [peachpiecompiler/peachpie#230]
i try to use composer and got some warning.
```
O:\project\psder\vendor\composer\autoload_real.php(26,133): warning PHP3006: Call to undefined function: 'zend_loader_file_encoded' [O:\project\psder\psder.msbuildproj]
O:\project\psder\vendor\composer\ClassLoader.php(345,21): warning PHP3006: Call to undefined function: 'Composer\Autoload\apcu_fetch' [O:\project\psder\psder.msbuildproj]
O:\project\psder\vendor\composer\ClassLoader.php(345,58): warning PHP3007: Undefined variable: $hit [O:\project\psder\psder.msbuildproj]
O:\project\psder\vendor\composer\ClassLoader.php(359,13): warning PHP3006: Call to undefined function: 'Composer\Autoload\apcu_add' [O:\project\psder\psder.msbuildproj]
```
i don't know how much effect does it cause. peachpie will compile all the included php fies, doesn't it?

**Comment by jakubmisek** [comment]
Yes, PeachPie will compile the PHP files and any call to an unknown function (like `zend_loader_file_encoded`) will be resolved at runtime. It may result in an error or a successful call to the function if the function is declared for example dynamically during the runtime. Anyway in this case; the warning means the function is not defined anywhere in the code and in case it will be called, it fails.

Check the source code:
```php
if (!function_exists('zend_loader_file_encoded') || !zend_loader_file_encoded())
```
the second condition causes the warning, however it will never be called because of the first condition.

In this case; you may ignore the warning.

**Comment by AutoDMC** [comment]
Is there a way to tell the PeachPie compiler to ignore a specific warning?  I've added some code to "define" the functions that composer is referring to to clean up my warnings, like below:

`
function apcu_fetch(...$x) {}; // Composer refers to this function, it's never called
`

Unfortunately, Composer has a variable named "$hit" that it doesn't define, and this causes two warnings in the compiler output.

Because this is Composer's auto generated file I can't just go in and "fix" the warning.

Is there a way to tell the compiler "I know this thing, please stop telling me about this" without having to do hacks like the above?

**Comment by jakubmisek** [comment]
I believe, `apcu_fetch` is called conditionally, so there is something like `if (function_exists("apcu_fetch")) apcu_fetch( ... );`

In this case you can ignore the warning and wait for compiler to be "smarter" in future - it will detect this case and won't warn about it.

To ignore specific warnings in general, please refer to `NoWarn` build property https://docs.peachpie.io/php/msbuild/#nowarn

Defining a dummy `apcu_fetch` function adds unnecessary overhead to the code, but works as well.
