### ISSUE TITLE
error PHPX2070

### ISSUE THREAD

**Issue by fleed** [peachpiecompiler/peachpie#241]
I'm trying to build an existing wordpress websites that uses some plugins. I'm getting the following error in one of the plugins:

```
error PHPX2070: Cannot access parent:: when current class scope has no parent
```

I'm using `Peachpie.Compiler.Tools 0.9.0-*`

The guilty code:

```
if (($first = reset($map)) && !is_array($first) && !is_numeric(key($map))) {
            parent::init($map, false); // line 124
            return;
        }
```

The containing class is abstract, so I guess that it implicitly assumes that there will be a parent class when running.

Any advice? Thank you

**Comment by bfistein** [comment]
Hi @fleed, thanks for submitting this. Which plugin causes this if you can disclose?

**Comment by bfistein** [comment]
This is an error in the actual PHP code of the plugin you are trying to compile, PeachPie isn't going to let you execute this. In regular PHP your app would crash if this piece code were ever used. In order to run this on PeachPie, fix the error in the PHP code and report it to the creators so that it will be fixed in the coming updates.

**Comment by fleed** [comment]
I understand, thank you
