### ISSUE TITLE
Unit tests for existing PHP projects

### ISSUE THREAD

**Issue by Remo** [peachpiecompiler/peachpie#324]
I've been keeping an eye on peachpie as I'd like to do more with .NET core, but I still have quite a PHP past and could thus benefit from something like peachpie. While I find it incredibly impression what you guys did so far, compatibility with existing code/libraries is essential to me and there are still quite a few little things to be tackled. I'm quite sure that applies to others too.

What I'd find great is a bunch of PHP libraries with xUnit tests to ensure that they work. We've seen in the past that it's probably hard to use the existing PHP tests, I guess it would be easier to create a bunch of new unit tests in C#.

Instead of creating issues like these:
* https://github.com/peachpiecompiler/peachpie/issues/317
* https://github.com/peachpiecompiler/peachpie/issues/290
* https://github.com/peachpiecompiler/peachpie/issues/313

Could there be an "official" way to verify the compatibility of PHP libraries with peachpie? Maybe another project where we can publish those libraries and add a number of unit tests?

Or should this just be a standalone .NET library outside of the peachpie organization? I'm hesitating about the latter because I wouldn't publish `Carbon\Carbon` as a standalone .NET library, I doubt anyone would use it in a C# only project. It might make sense for `box/spout` as it would have some value for other .NET developers, not only those coming from PHP.

What is your opinion about that?

**Comment by jakubmisek** [comment]
Very well said, reasonable point. It is probably a good time to start testing the compatibility (we have been waiting since there are still a few architectural issues and we are working on them).

Actually we are already running PHPUnit (https://github.com/iolevel/frameworks-ci/tree/master/phpunit) if you just copy `phpunit.phar` into the root, the project builds an executable and you can run it just like that (with arguments for the phpunit)

Integration with xUnit *will* be possible once the compiler start generate parameter-less constructors. We don't have an issue for that, will do. Custom attributes are already supported. Only Visual Studio UI might get confused. What will be a perfect solution would be an "adapter" for "dotnet test" that would run compiled phpunit (just thinking...) with right interfaces for VS and other IDE's.
