### ISSUE TITLE
System.NotImplementedException: 'Cannot implicitly convert 'String' to 'String'.

### ISSUE THREAD

**Issue by crbrz** [peachpiecompiler/peachpie#406]
Compiling this [project](https://github.com/crbrz/wpdotnet-sdk) with this command `dotnet build -c Debug -m:1 -nr:false` gives this error: `Cannot implicitly convert 'String' to 'String'. not implemented at C:\Work\wpdotnet-sdk\PeachPied.WordPress.StorefrontTheme\wp-content\themes\storefront\inc\storefront-functions.php(154, 1)`. Peachpie version is 0.9.38 with dotnet 2.2.202. The reported line number seems to be off by 1 (zero based?).

I've been getting these errors in a similar project but only at random times most likely depending on how the individual projects are distributed between the dotnet processes spawned to handle the solution build. I think the issue might have something to do with running Peachpie compiler directly inside dotnet (or msbuild) host process ([8b311e028f29cbf0b8f135689edfd73170da9820](https://github.com/peachpiecompiler/peachpie/commit/8b311e028f29cbf0b8f135689edfd73170da9820)). By forcing the build to run in a single dotnet process the error occurs each time the solution is built. The error doesn't occur when compiling with 0.9.36.

**Comment by jakubmisek** [comment]
I see! Since the compiler lives in the MSBuild Task now and the process is reused by Visual Studio for subsequent compilations, all the static variables survive.. clearing the statics (https://github.com/peachpiecompiler/peachpie/pull/411) works for now, we'll try to fix it properly and make use of the MSBuild process pooling.
