### ISSUE TITLE
PEAR_Error is not implemented

### ISSUE THREAD

**Issue by liesauer** [peachpiecompiler/peachpie#528]
i try to compile [ecshop](https://github.com/shopex/ecshop) project which is a famous online mall system(at least in china) and get this error:
```
/Users/imac/Projects/ecsharp/Website/ecshop/upload/includes/shopex_json.php(820,39): error PHP4044: Type name 'PEAR_Error' could not be resolved. [/Users/imac/Projects/ecsharp/Website/Website.msbuildproj]
```

btw, @jakubmisek do u mind opening a `ECShop` project?

**Comment by jakubmisek** [comment]
`PHP4044` indicated the class does not exist and is needed to compile the code properly. You can workaround it by commenting out the piece of code using PEAR_Error.

We don't have any plans to support PEAR since it is a deprecated functionality.

--

ECShop is a nice idea, however we don't have a plan to support it by ourselves - at least we can assist you with issues and fix what is necessary.

**Comment by jakubmisek** [comment]
in WordPress we workaround `PEAR_Error` by commenting the code out

@liesauer we'll open `ECShop` project but with a note that we are not responsible :)

**Comment by liesauer** [comment]
ok

**Comment by jakubmisek** [comment]
test case:
```php
class Err extends PEAR_Error {
}
```

**Comment by ethan-tqa** [comment]
Got hit by the same error, but this time with latest Wordpress, version 5.2.3

**Comment by jakubmisek** [comment]
yes, we are removing the use PEAR_Error from the sources for now

**Comment by jakubmisek** [comment]
Closing the issue:

Workaround #1: add dummy `PEAR_Error` class into your code
Workaround #2: remove (Exclude) code that uses `PEAR_Error` since it is probably not being used anyways
