### ISSUE TITLE
PCRE_ANCHORED ("A") flag not implemented in preg_match

### ISSUE THREAD

**Issue by Fezzzi** [peachpiecompiler/peachpie#531]
Enclosing minimal PHP [script](https://github.com/peachpiecompiler/peachpie/files/3593010/program.txt) demonstrating the error encountered. This code is executed during Twig template rendering, in a process of tokenization in `twig\twig\src\Lexer.php`, where can be found more such regular expressions as well.

Output in PHP 7.1.8 :
```
got: 0
expected: 0 
```

Output from C# using Peachpie.NET.Sdk version 1.0.0-appv2800:
```
got: 1
expected: 0
```

**Comment by jakubmisek** [comment]
thank you! can we have the script more "minimal" ? :)

**Comment by roberthusak** [comment]
We examined the problem with @Fezzzi further and it was due to the missing implementation of the `PCRE_ANCHORED` (`A`) flag. The smallest test case is probably:
```php
echo (int)preg_match('/b/A', 'ab', $match);
```
Expected `0`
Actual `1`

I implemented it in https://github.com/peachpiecompiler/peachpie-perlregex/commit/36105c80bcf7bfa7fe8fa6eeaefa00ff40c9d366. Once it's referenced from Peachpie, it should work. @Fezzzi, can you please check that it works in the bigger sample when using the latest `peachpie-perlregex` commit?

**Comment by jakubmisek** [comment]
thank you @roberthusak  and @Fezzzi !

**Comment by Fezzzi** [comment]
Yes, the tokenization phase of the Twig template rendering is now operable, therefore the problem seems resolved. Thank you for the quick action!

**Comment by roberthusak** [comment]
Great, so we can mark this as resolved as soon as we use the latest changes of `peachpie-perlregex` from here. @jakubmisek Can I bump its version to `1.0.4`?

**Comment by jakubmisek** [comment]
will do, thank you!

@roberthusak how hard would it be to implement `D` and `X` modifiers ?

**Comment by roberthusak** [comment]
@jakubmisek It should be quite easy, I'll look into that now.

**Comment by roberthusak** [comment]
@jakubmisek Done in https://github.com/peachpiecompiler/peachpie-perlregex/commit/95feb7f80c4dd683ab36de7b8556e8f4d2a2e624 and https://github.com/peachpiecompiler/peachpie-perlregex/commit/968d53661f04abe7af01b91f9b9024c16a6fbf5c
