### ISSUE TITLE
Mismatch with PHP behaviour in using call_user_func_array inside namespace

### ISSUE THREAD

**Issue by roberthusak** [peachpiecompiler/peachpie#562]
Test case (`functions/callback_002.php` with added namespace):
```php
namespace someNS;

class A {
    function foo($x) {
        echo __METHOD__;
    }
}

class B {
    function foo($x) {
        echo __METHOD__;
    }
}

$x = new A();
call_user_func_array([&$x, "foo"], [$x = new B]);
echo " Done.";
```
Expected: ```someNS\B::foo Done.```
Actual: ```A::foo Done.``` 

If `namespace someNS;` is not present, PHP yields `A::foo Done.` as well and the test passes succesfully. TBH it seems like some sort of black magic..

**Comment by jakubmisek** [comment]
but `call_user_func` has nothing to do with current `namespace`

**Comment by jakubmisek** [comment]
haha I found it - `call_user_func_array` in a namespace is ambiguous between
- `\call_user_func_array`
- `\someNS\call_user_func_array`

since it is ambiguous, it is resolved in a different order than it would be outside of namespace

by specifying `\call_user_func_array( .. );` you'll get expected result in PHP

**Comment by roberthusak** [comment]
Ah.. that makes sense, thanks.

**Comment by jakubmisek** [comment]
yep, and PeachPie assumes `\call_user_func_array` and does not postpone it to run time .. (which is also a bug but by design)
