### ISSUE TITLE
pcre pattern does not match unicode characters

### ISSUE THREAD

**Issue by jakubmisek** [peachpiecompiler/peachpie#738]
Following pattern supposes to match UTF8 byte sequences:

```php
$regex = '/
	(
	(?: [\x00-\x7F]                  # single-byte sequences   0xxxxxxx
	|   [\xC2-\xDF][\x80-\xBF]       # double-byte sequences   110xxxxx 10xxxxxx
	|   \xE0[\xA0-\xBF][\x80-\xBF]   # triple-byte sequences   1110xxxx 10xxxxxx * 2
	|   [\xE1-\xEC][\x80-\xBF]{2}
	|   \xED[\x80-\x9F][\x80-\xBF]
	|   [\xEE-\xEF][\x80-\xBF]{2}
	|   \xF0[\x90-\xBF][\x80-\xBF]{2} # four-byte sequences   11110xxx 10xxxxxx * 3
	|   [\xF1-\xF3][\x80-\xBF]{3}
	|   \xF4[\x80-\x8F][\x80-\xBF]{2}
	){1,40}                          # ...one or more times
	) | .                            # anything else
	/x';
```

The pcre replaces sanitized string by keeping only matched characters:

```php
$value = preg_replace( $regex, '$1', $value );
```

for `$value = "rřsšcč";`
Expected: `"rřsšcč`
Actual: `"rsc"`

**Comment by jakubmisek** [comment]
Note: this causes WordPress to fail to save any options containing Unicode characters

**Comment by roberthusak** [comment]
Fixed in https://github.com/peachpiecompiler/peachpie-perlregex/commit/25d7e150462d6dcc8aec8489af2dfbd0f9cd22bb and https://github.com/peachpiecompiler/peachpie-perlregex/commit/11748169b5125a2c46e0f4339907d8436211c05c. Bumping version of `Peachpie.Library.RegularExpressions` and referencing it should solve this.
