### ISSUE TITLE
is_readable vs file_exists issue for PHP files

### ISSUE THREAD

**Issue by Indigo744** [peachpiecompiler/peachpie#814]
Hello,

I am trying to run our legacy app on PeachPie (sweet project by the way 😄), and there are some issues.

The `is_readable()` function is used extensively throughout the code base to check if a file is available before including or working with it. However, it does not work in PeachPie.

However, using `file_exists()` actually resolves the issue.

Here is a minimum code to highlight the difference:
```php
<?php // in index.php file
echo "is_readable('index.php') = " . (is_readable('index.php') ? "YES" : "NO") . "\n";
echo "file_exists('index.php') = " . (file_exists('index.php') ? "YES" : "NO") . "\n";
die();

/* returns
is_readable('index.php') = NO
file_exists('index.php') = YES
*/
```

Thank you.

**Comment by jakubmisek** [comment]
This is actually right, because the file is not readable unless you add it to your application as a content.

All the source files are compiled and they are not copied to the build output. In case you need to read their content, you have to add the file into the build output. To do so, edit your project file:
```xml
<ItemGroup>
  <Content Include="the_file" />
<ItemGroup>
```

**Comment by Indigo744** [comment]
I _guess_ I understand, it makes sense.

However, I fear a lot of code uses `is_readable()` before including files (as did ours), which would lead to incompatibilities because they don't want to really "read" them (and adding every possible PHP file as `<Content>` is not feasible).

I'm not sure what would be the best approach here...

**Comment by jakubmisek** [comment]
You're right. I guess developers have to keep it in mind when they want to migrate from PHP to .NET .. maybe we can report a compile-time warning in similar cases?

**Comment by Indigo744** [comment]
If you are able to recognize these kind of fragments, that would be good.

To add more information, our legacy app is based on a framework which is based on an old ZendFramework version 1. Yeah, I know...
Most lib called this [`isReadable()` static method](https://github.com/zendframework/zf1/blob/master/library/Zend/Loader.php#L162) before actually loading the file with `loadFile()`.

In this case, I don't think there would be an easy way to do this...

Maybe a specific page documenting this behavior, and how to handle this would be great 😸

**Comment by jakubmisek** [comment]
I see. You're right, in this case we won't be able to recognize it for sure.

For legacy applications, it is safer to include the source files using smth like `<Content Include="**" />` because it is the only 100% compatible solution (apps sometimes for no good reason read the content of the source files).

In the future, internally PeachPie might use some kind of file-system abstraction (like `IFileProvider` in ASP.NET Core) where this behavior could be overriden.

For now, the functions do what they say :) Maybe we can report a warning when `is_readable()` is used?

**Comment by Indigo744** [comment]
> Maybe we can report a warning when is_readable() is used?

Maybe only a warning if it is a PHP file? Or only if not found?

**Comment by jakubmisek** [comment]
I was thinking about compile-time warning whenever there is `is_readable` in the source code. The argument is usually a variable so we don't know it's a PHP file yet

**Comment by jakubmisek** [comment]
`is_readable()` now signalizes `true` for compiled files as well. Since https://github.com/peachpiecompiler/peachpie/commit/392c44e20e37ba42b1609a1265fb800fbc1f1f63
