### ISSUE TITLE
PHAR support

### ISSUE THREAD

**Issue by jakubmisek** [peachpiecompiler/peachpie#83]
Compilation directly from PHAR, inclusion of files in PHAR, including PHAR stub.

The goal of this issue is to be able to compile phpunit from phar.

### Classes
- [x] [Phar](http://php.net/manual/en/class.phar.php)
- [x] [PharData](http://php.net/manual/en/class.phardata.php)
- [x] [PharFileInfo](http://php.net/manual/en/class.pharfileinfo.php)
- [x] PharException

### Runtime
- [x] include of a `phar://`
- [x] `phar://` stream wrapper
- [x] `phar://` alias ([mapPhar](http://php.net/manual/en/phar.mapphar.php))

### Compiler
- [x] PHAR file parser
- [x] compilation of `.phar` file
- [x] skip first line of phar stub (`#!/usr/bin`)
- [x] magic constants inside PHAR entries (`__FILE__` etc)
- [x] [StartupObject](https://docs.peachpie.io/php/msbuild/#startupobject) to be `.phar` file
- [x] PHAR content files into resources

**Comment by gordon-matt** [comment]
+1. I've noticed a couple of compiler warnings (related to issue #185) where the message is as follows:

`Class 'PharData' not found`

Only 2 instances found, both as follows: `$phar = new PharData($path);`

**Comment by theofidry** [comment]
If you want to double check you can also test on a library such as [Box](https://github.com/humbug/box) which is a PHAR builder and should cover the most common cases.

**Comment by deinok** [comment]
Hi, first of all, I'm not very good with PHP so I this could be wrong.
Probably your aproach is better, but this could add the feature for now.

Have you looked at the aproach of:
* Detect *.phar
* Uncompress the *.phar
* Interpretate as normal *.php

Some refs:
http://unphar.com/index.php

**Comment by theofidry** [comment]
@deinok while it makes sense if you are unfamiliar with PHARs, there is a downside to it: you will not get the same behaviour.

Unfortunately the PHAR extension is what it is: a quirk implementing a compressed format all over again unlike a `.jar` file which is more akin to a regular archive with a manifest. So there is some stuff not working the same, for example `real_path()` will not provide the same values for a file from the PHAR since it's a virtual file.

So if you are looking for consistency, I don't think there is a way around it. I however would strongly advise to consider not replicating some quirk behaviours (which in return should be documented). When working on Box, I could find a couple of behaviours which IMO are very undesirable and for which there is no point to replicate:

- The whole HTTP support: there is no good reason to use a PHAR for the web anymore; that said it's probably the most debatable point of my list
- The metada behaviour: right now the metadata is serialized/unserialized. I don't know when this will be patched, but can be a security hole if you were thinking just reading a PHAR couldn't trigger anything
- Unable to compress the PHAR when there is an OS limit to the maximum number of files when the PHAR has too many files: in Box I check the number of files to include and bump it when necessary

Maybe there is more, but this is what I got on top of my head

**Comment by jakubmisek** [comment]
@theofidry great notes. Also we don't plan to support packing PHARs, only consuming during the compilation.
