### ISSUE TITLE
PeachPie useable for php scripts with encrypted source code?

### ISSUE THREAD

**Issue by mclauncherlinux** [peachpiecompiler/peachpie#878]
Can PeachPie be used for php script/apps that have their code encrypted/decoded ?

**Comment by jakubmisek** [comment]
Hi, what kind of encoding do you mean, an obfuscation?

In case the code has been obfuscated, it is still a valid PHP code that can still be compiled.

**Comment by DRSDavidSoft** [comment]
I believe he is referring to source code that is obfuscated using products such as [Zend Guard](https://www.zend.com/products/zend-guard) and [ionCube](https://www.ioncube.com/), in which case, I don't believe PeachPie can compile them -- since they do not use valid PHP code at all.

These products require the use of a Zend extension to be loaded within PHP, which parses their own proprietary format of bytecode.

**Comment by jakubmisek** [comment]
Right, in case the code is encoded into a proprietary byte code, PeachPie won't compile it.
